# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation ui:      !include automations.yaml          # created/edited in the UI
automation manual:  !include_dir_merge_list automations  # your CLI yaml files

script ui:     !include scripts.yaml                          # UI scripts only
script manual: !include_dir_merge_list scripts                # your CLI yaml files
scene ui:      !include scenes.yaml                    # UI scenes
scene manual:  !include_dir_merge_list scenes          #  scenes/quick_actions.yaml

 
# make the Living-room light-group load
light: !include_dir_merge_list lights


logger:
  default: info
  logs:
    custom_components.zeptrion_custom: debug

# Optional: explicitly register the YAML dashboard
lovelace:
  dashboards:
    md3-dashboard:
      mode: yaml
      title: Main
      icon: mdi:home
      filename: dashboards/ui-main.yaml
      show_in_sidebar: true

